name: John Allen
favicon: null
layout_spectrum: 0.5358380549587309
typography_spectrum: 0.0688839687500149
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.020894228015094995
  lightness: 0.652723275590688
  saturation: 0.36634719371795654
  rhythmicContrast: 0.163697958458215
purpose: []
